name: Build and publish

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: node_modules-${{ matrix.node-version }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: packages/*/bundles/**/*.js

      # TODO
      # - name: Publish
      #   run: yarn semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
