name: Build and publish

on:
  pull_request:
    branches: [main]

jobs:
  code-check:
    name: Code check

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: node_modules-${{ matrix.node-version }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test

      - name: Typecheck
        run: yarn run typecheck
